### ISSUE TITLE
org-download-screenshot locks keyboard input

### ISSUE THREAD

**Issue by matthewdeancooper** [abo-abo/org-download#140]
When using org-download-screenshot I cannot use my window manager (DWM) keybindings to navigate to what I would like to screenshot. All keyboard input is non-responsive. Additionally, org-download-clipboard does not seem to be defined for me - which could act as a workaround. Cheers

**Comment by sunnyrahul25** [comment]
Commenting, if someone ran into same problem.
I frequently use org-download screenshot method but since last few months gnome-screenshot is not working.
I tried [shotgun](https://github.com/neXromancers/shotgun)  with [hacksaw](https://github.com/neXromancers/hacksaw),  as org-download screenshot method and it works flawlessly. You can also switch between workspaces while capturing screen shot.

**Comment by nilanfernando31** [comment]
> Commenting, if someone ran into same problem.
> I frequently use org-download screenshot method but since last few months gnome-screenshot is not working.
> I tried [shotgun](https://github.com/neXromancers/shotgun) with [hacksaw](https://github.com/neXromancers/hacksaw), as org-download screenshot method and it works flawlessly. You can also switch between workspaces while capturing screen shot.

Can u tell please how did you modify the org-download-screenshot-method for shotgun with hacksaw.. I am unable to find them on value menu

**Comment by sunnyrahul25** [comment]
(setq org-download-screenshot-method "shotgun -g $(hacksaw) %s")
