### ISSUE TITLE
org-download-clipboard does nothing

### ISSUE THREAD

**Issue by ggufeng** [abo-abo/org-download#208]
Hi, I am using spacemacs (0.300.0@27.1) under Windows 10.
The org-download is configured as suggested in README.md:
```
(require 'org-download)

;; Drag-and-drop to `dired`
(add-hook 'dired-mode-hook 'org-download-enable)
```
But when I try to insert an image from clipboard with org-download-clipboard, nothing happens. Could anyone tell me how to troubleshoot this?

**Comment by eecsfuture** [comment]
Hi, endlessMagic
I have the same problom, org-download-clipboard does nothing, but the drag-and-drop can work well.
I have installed the imagemagick and convert.
How do you solve this problom?

**Comment by Horrih** [comment]
See issue [207](https://github.com/abo-abo/org-download/issues/207) and [pull request 184](https://github.com/abo-abo/org-download/pull/184)

Since it is not merged yet, here is a TL;DR :
- install ImageMagick and have it on your path
- in org-download.el : fix the org-download-clipboard method by replacing all occurences of "convert" by "magick"
- make sure to remove org-download.elc if it exists, otherwise emacs will not use your modified version
