### ISSUE TITLE
improve org-download add link way

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/org-download#27]
I found org-download download image by inserting string like org-mode attachment property filename, and link at first, then start async downloading.

But when the downloading fails, Then I remove link string, (have not remove attachment property filename). When I try to re-download image, it always failed.
The error log message in ~*Messages*~:
```
File "dashboard_files_tab_2015-10-29_20-41-13.png" is now a task attachment.
error in process sentinel: apply: Symbol's value as variable is void: link
error in process sentinel: Symbol's value as variable is void: link
```
Here is the test image link: http://nbviewer.ipython.org/github/ipython/ipython/blob/3.x/examples/Notebook/images/dashboard_running_tab.png

I think download might can improve on this.
And org-download has command `org-download-remove`, but it does not work as I think. I only remove current point line image link.

**Comment by abo-abo** [comment]
> File "dashboard_files_tab_2015-10-29_20-41-13.png" is now a task attachment.

I have no problem with this. However, your file name looks different from mine: `dashboard_running_tab_2015-10-29_14:19:56.png`.

I downloaded as an attachment, deleted the file from `dired`, downloaded again to a different file name (due to the time stamp).
Now `:Attachments:` has 2 files, one of which doesn't exist any more. Otherwise it's fine.

> And org-download has command org-download-remove, but it does not work as I think.

I think you mean `org-download-delete`: it removes the link at point and deletes the file.
For attachments, it only deletes the file, doesn't remove the attachment entry.

**Comment by stardiviner** [comment]
I know my network is behind China firewall. I use proxy for Emacs with `export HTTP_PROXY=...`. Because sometimes GitHub is not available for me.
I think `org-download-delete` can delete the attachment entry too.
After your test, I think I failed many times must be on network issue.

**Comment by abo-abo** [comment]
> must be on network issue

I think so too. Anyway, I made `org-download-delete` sync attachments as well.

**Comment by stardiviner** [comment]
Thanks @abo-abo
