### ISSUE TITLE
org-download on a remote file via tramp/ssh.. a solution?

### ISSUE THREAD

**Issue by zeltak** [abo-abo/org-download#37]
Hi :)

this maybe not totally directed to org-download but ill ask anyway.

when i open a org file via TRAMP and edit it (i use sshx if that matters) i cant seem to use org-download to add images to the file and i get this error:

```
gm import: Unable to open XServer ().
url-retrieve-internal: Bad url: /tmp/screenshot.png
```

i wonder if there is a solution for this in anyway?

thx alot

Z

**Comment by abo-abo** [comment]
I think it should simply work because of Emacs TRAMP magic. But if it doesn't, I don't have too much time to debug such a rare situation.

Maybe you could edit your project locally, commit in Git and push? And then Git pull to have your work on the remote as well.

**Comment by wandersoncferreira** [comment]
I haven't debugged it, but this problem is very similar to one I experienced before.

When you make use of `shell-command` over TRAMP sessions, Emacs tries to execute the command in the remote machine. So, as your remote server has no Xserver you get this error when you try to access gm.

You could solve this issue by adding a `org-download-prefer-local` flag and switching the `shell-command` to something like this `call-process "/bin/bash" nil nil nil "-c" ` when the flag were true.

**Comment by abo-abo** [comment]
@wandersoncferreira You're right, it might actually be a well-defined behavior to download the image /on the remote/. Maybe it's not what the user expects though.
