### ISSUE TITLE
Invalid function: async-start

### ISSUE THREAD

**Issue by binxboll** [abo-abo/org-download#7]
On Mac OS X 10.8.5, I am running GNU Emacs 24.3.1 (x86_64-apple-darwin12.5.0, Carbon Version 1.6.0 AppKit 1187.4). I have installed the latest version of org, including the org-download from contrib, Org-mode version 8.2.5h (release_8.2.5h-653-g64adcc). I have also installed the latest async via melpa.

When I drag and drop a png file onto an org buffer, I get the following error:
Invalid function: async-start

I get the same error when I invoke 
M-x org-download-image
and enter a valid image url at the prompt.

Any idea what I am doing wrong?

**Comment by loochao** [comment]
Does org-download work under Mac OSX?
I believe I've installed org-download.el correctly, but when I'm dragging and drop the image into an org buffer, all I get is the link address inserted into the buffer, no downloading events trigger.

I double checked a few things before coming here:
- My system has both curl and download.
- I've set the download image dir to ~/Downloads/Foo
- The value of dnd-protocol-alist contains ("^\\(https?\\|ftp\\|file\\|nfs\\)://" . org-download-dnd)

The emacs I'm using is "GNU Emacs 24.3.1 (x86_64-apple-darwin, NS apple-appkit-1038.36) of 2013-03-13 on bob.porkrind.org"

Could someone help? Thanks a lot.

**Comment by abo-abo** [comment]
I don't have OSX, so I can't test it.  However, it should work in
theory, since all tools used are portable.

Try using `org-download-yank` first: this one does everything except
dnd. Just right click and copy image url in the browser, and call
`org-download-yank` in Emacs. If it doesn't work, the issue is with
dnd, otherwise it's with the downloading itself.

The default `org-download-backend` uses `url-retrieve`, which is part of
Emacs, so if it doesn't work then it's a bug.

**Comment by abo-abo** [comment]
It seems that this issue is fixed for Emacs 24.4.1.

**Comment by mankoff** [comment]
I just ran into this issue using Org (latest git head), org-download (latest melpa) and emacs-mac. The solution was to delete the ELC files from the elp/org-download folder.
